# Generated by Django 4.1 on 2022-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('S', 'sent'), ('R', 'recieved')], max_length=1),
        ),
    ]
